### ISSUE TITLE
Empty flag should only erase related files

### ISSUE THREAD

**Issue by Montspy** [sk33z3r/LooPyGen#14]
`metadata.py -e` flag should only erase JSON files 
`generate.py -e` flag *could* only erase image files and the few JSON files it generates, but open to keeping it as erase all files

**Comment by sk33z3r** [comment]
I agree with this. Since there is a seed now, perhaps we leave the metadata alone. Gonna think on that before we put something in.

I agree that `metadata -e` should _only_ clear metadata.

**Comment by Montspy** [comment]
The folder structure changed and metadata are now separated from images.
This issue is addressed by that change.
Can we close?

**Comment by sk33z3r** [comment]
Yea, I meant to close before :+1:
