### ISSUE TITLE
Option to allow transparent backgrounds or default to a color

### ISSUE THREAD

**Issue by sk33z3r** [sk33z3r/LooPyGen#15]
Some folks might want transparency, some might not.

An option to select one or the other would be great.

We might want to take it a step further by allowing the user to select a set of colors that get randomly picked for a default BG color.

**Comment by Montspy** [comment]
Pushed working draft to `dev/backgrounds` for testing.
New `traits.example.py`

**Comment by Montspy** [comment]
#22

**Comment by sk33z3r** [comment]
Closed the PR, I think the solution is perfect. Closing this ticket.
