### ISSUE TITLE
Add batch CID script for users that only want to mint and don't use the generator

### ISSUE THREAD

**Issue by sk33z3r** [sk33z3r/LooPyGen#26]
@Montspy Do you think we should make this a feature of the `LooPyGen` or for `LooPyMinty`?

I could see the argument that if someone doesn't want to generate images, they only want to batch mint. Obviously with the way you implemented batch minting the user can just use your repo.

The only argument to make it a feature in this repo is to funnel everyone to a single place for all the needs.

---

In this scenario, I think the user would be responsible for making their own metadata files and pre-filling them with the right CIDs.

Then our function can simply iterate a folder of metadata, build the CID json, then run a mint.

**Comment by Montspy** [comment]
Been working on that here: https://github.com/Montspy/LooPyMinty/tree/dev/collection-minter
It's not super user-friendly but it can:
1. Prepare empty templates of metadata JSON files from a folder full of images
```plaintext
./docker.sh prepare --idir ./path/to/nft_images/ --metadata
```
2. Pre-calculate the CID hashes from a folder ready-to-mint metadata JSON files
```plaintext
./docker.sh prepare --idir  ./path/to/nft_metadata/ 

For integration with LooPyGen, we could add a --odir to redirect the output

**Comment by sk33z3r** [comment]
Of course you've already got this! I like it, and adding an `--odir` would be needed, maybe as a hard-code into the `mint.sh` script.

I could see maybe dumping the `mint-info.json` file in the same place as the rest of our generated stuff, too. So maybe the `--odir` flah should actually be a part of the new `--loopygen` flag idea?

**Comment by Montspy** [comment]
`mint-info.json` was intended for debug purpose
Unless you have a use for it in LooPyGen, I'd like to keep it within LooPyMinty

I can add `--loopygen` that redirects the output dir to `./generated/` for now

**Comment by sk33z3r** [comment]
Ahh, I see. I am getting mint-info.json in LooPyGen folder because LooPyMinty just stores it in the top level. It's no big deal really, we just leave that one along.

**Comment by Montspy** [comment]
Hmm, I'll make it output `mint-info.json` to the python script's path rather than to the current working directory

**Comment by Montspy** [comment]
Features are part of https://github.com/Montspy/LooPyMinty/pull/15
