### ISSUE TITLE
[PHP] Generate traits.json using only file/folder names

### ISSUE THREAD

**Issue by sk33z3r** [sk33z3r/LooPyGen#35]
I'm beginning to see this as a nice-to-have instead of mandatory. Will be a great feature eventually.

Besides PHP to do the work, we'll also need some good documentation so the users know precisely how to setup their folders for this to work properly.

**Comment by Montspy** [comment]
Agree it's a nice-to-have at this point

**Comment by sk33z3r** [comment]
New React UI in the works, closing the PHP tickets.
