### ISSUE TITLE
[UI] Button to nuke sensitive information

### ISSUE THREAD

**Issue by Montspy** [sk33z3r/LooPyGen#51]
I'd like to add an easily reachable button in UI to nuke all sensitive info (mainly private keys) from disk
It could simply remove the `config.json` file and provide confirmation

**Comment by Montspy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Nuke sensitive info button](https://trello.com/c/PooSJEG6/26-nuke-sensitive-info-button)

**Comment by sk33z3r** [comment]
Added with 17be98adccac3da76e289d71831ea0c56c51b116

**Comment by Montspy** [comment]
Verified! Will close when it makes into the main branch
