### ISSUE TITLE
/loopygen should be writeable by PHP

### ISSUE THREAD

**Issue by Montspy** [sk33z3r/LooPyGen#64]
![image](https://user-images.githubusercontent.com/2715455/173790911-fbc1e12b-bee5-452a-b836-15f77efb46cd.png)

Current directory `/loopygen` doesn't allow writes from users other than `root`
PHP's `www-data` user calls python which tries to create a temp folder in `/loopygen` and fails

I can also move the temp folders to `/tmp`

**Comment by sk33z3r** [comment]
Should be resolved with https://github.com/sk33z3r/LooPyGen/pull/47/commits/a41059597aede46ad6b09b33a7489e8788115b0b
