### ISSUE TITLE
Make the result box for generation, metadata, mint, transfers wider if necessary

### ISSUE THREAD

**Issue by Montspy** [sk33z3r/LooPyGen#65]
![image](https://user-images.githubusercontent.com/2715455/173803903-cbe3db06-2dc9-42f0-a2f9-381aa3f60c0e.png)

Current box cuts off a lot of the details in case of errors

**Comment by sk33z3r** [comment]
I'm awesome and linked my commit to the wrong bug

https://github.com/sk33z3r/LooPyGen/commit/6d003013bc2bdb5c8c6d4869768c323a240c8002
