### ISSUE TITLE
[PHP] Generate "traits.py" via PHP frontend

### ISSUE THREAD

**Issue by sk33z3r** [sk33z3r/LooPyGen#7]
It would be nice to have a web form where users could enter information in a more streamlined way, then output json for use in python.

**Comment by sk33z3r** [comment]
We should make this a localized UI, that is never hosted anywhere. This is only to give the user a nice entry form to make their traits and generate the proper environment files we need to run the generators.

The other reason we do it locally is so that we can take in the private keys and save them to the .env without allowing that key to get passed online anywhere.

This should curb a LOT of confusion in the setup, but is going to require some logic to put together.

**Comment by sk33z3r** [comment]
@Montspy Do you think this is too much? I'm not sure if we should put the minting stuff in here or not. Just an initial idea, open to ideas.

https://github.com/sk33z3r/LooPyGen/blob/dev/json-traits/traits.example.json

**Comment by Montspy** [comment]
Since the goal is to remove the need for the user to even think about `.env`, we should add the following to some json configuration file:
Account ID, NFT type, Fee token ID
We could split generation and minting config files into 2:
`traits.json` and `mint.json` to avoid confusing users that on-board and just want to generate for now.

**Comment by sk33z3r** [comment]
That makes sense. I suppose we have the user create and place `traits.json` into each of their collection folders, then `mint.json` can stay in the top level since it is universal.

I think we should continue to make the PK the sole item in `.env` just so it's isolated, and no one accidentally shares it with `mint.json` config. Perhaps the API key should remain in `.env` as well, no one really has a need to share either of those two items.

On the front end, I will still ask for all the info and separate out for them.

**Comment by Montspy** [comment]
For the API key, I created issue https://github.com/Montspy/LooPyMinty/issues/16
We could get it from Loopring's API https://docs.loopring.io/en/dex_apis/getApiKey.html

**Comment by sk33z3r** [comment]
Oh, I like that. Less the user has to copy into files from the export, as well.

**Comment by sk33z3r** [comment]
PR #34 opened

**Comment by sk33z3r** [comment]
@Montspy Here is the output JSON that the generator will need to pull in for traits and setting up a collection

https://github.com/sk33z3r/LooPyGen/blob/dev/json-traits/traits.example.json

**Comment by sk33z3r** [comment]
Feature is implemented as of #34
