### ISSUE TITLE
Allow a single wallet to be entered multiple times for transfer

### ISSUE THREAD

**Issue by sk33z3r** [sk33z3r/LooPyGen#76]
Instead of culling the list of duplicates, we should let them be. This way if someone transfers a collection and a few wallets ordered 2 of an item, then they can just paste the wallet twice and the system _should_ just run a second transfer as normal.

**Comment by Montspy** [comment]
My bad! This is already the default behavior:
Here is the `--random` transfer of NFTs to the same wallet twice
![image](https://user-images.githubusercontent.com/2715455/175189442-2132e556-5cd6-43f1-9a60-14f130e50e61.png)
Closing
